### ISSUE TITLE
libssl-dev is missing to compile Net::SSLeay

### ISSUE THREAD

**Issue by ikus060** [rkerr/netdisco-vagrant#1]
package "libssl-dev" should be added as dependencies to allow compilation of  Net::SSLeay

**Comment by rkerr** [comment]
Thanks, I guess at some point starman changed to depend on Net::SSLeay. eef4644 changes the dependencies to pull down libcrypt-ssleay-perl (there didn't seem to be a good reason to compile it from scratch anyway).

**Comment by ikus060** [comment]
Super !
Thanks alot !
